name: Run tests and build docs
on:
  push:
    branches: master
  pull_request:
    branches: master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python: ['3.8', '3.9', '3.10', '3.11', '3.12']
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v4
    - name: Install Conda environment with Micromamba
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python }}
        environment-file: yeadon-dev-env.yml
        activate-environment: yeadon-dev
        miniforge-version: latest
    - name: Run nose
      shell: bash -l {0}
      if: runner.python-version != '3.12'
      run: |
        nosetests -v --with-coverage --cover-package=yeadon
    - name: Run pytest
      shell: bash -l {0}
      if: runner.python-version == '3.12'
      run: |
        conda install pytest
        coverage run -m pytest yeadon
    - name: Build the documentation
      shell: bash -l {0}
      run: |
        cd doc && make html
    - name: Install the software
      shell: bash -l {0}
      run: |
        python setup.py install
        yeadon -h
